package org.accenture.entities;

import lombok.Getter;

@Getter
public class Trait {
    private Symbol symbol;
    private String name;
    private String description;

    public String getSymbol() {
        return symbol.name();
    }

    private enum Symbol {
        BUREAUCRATIC, SECRETIVE, CAPITALISTIC, INDUSTRIOUS, PEACEFUL, DISTRUSTFUL, WELCOMING, SMUGGLERS, SCAVENGERS,
        REBELLIOUS, EXILES, PIRATES, RAIDERS, CLAN, GUILD, DOMINION, FRINGE, FORSAKEN, ISOLATED, LOCALIZED, ESTABLISHED,
        NOTABLE, DOMINANT, INESCAPABLE, INNOVATIVE, BOLD, VISIONARY, CURIOUS, DARING, EXPLORATORY, RESOURCEFUL,
        FLEXIBLE, COOPERATIVE, UNITED, STRATEGIC, INTELLIGENT, RESEARCH_FOCUSED, COLLABORATIVE, PROGRESSIVE,
        MILITARISTIC, TECHNOLOGICALLY_ADVANCED, AGGRESSIVE, IMPERIALISTIC, TREASURE_HUNTERS, DEXTEROUS, UNPREDICTABLE,
        BRUTAL, FLEETING, ADAPTABLE, SELF_SUFFICIENT, DEFENSIVE, PROUD, DIVERSE, INDEPENDENT, SELF_INTERESTED,
        FRAGMENTED, COMMERCIAL, FREE_MARKETS, ENTREPRENEURIAL, UNCHARTED, UNDER_CONSTRUCTION, MARKETPLACE, SHIPYARD,
        OUTPOST, SCATTERED_SETTLEMENTS, SPRAWLING_CITIES, MEGA_STRUCTURES, PIRATE_BASE, OVERCROWDED, HIGH_TECH,
        CORRUPT, TRADING_HUB, INDUSTRIAL, BLACK_MARKET, RESEARCH_FACILITY, MILITARY_BASE, SURVEILLANCE_OUTPOST,
        EXPLORATION_OUTPOST, MINERAL_DEPOSITS, COMMON_METAL_DEPOSITS, PRECIOUS_METAL_DEPOSITS, RARE_METAL_DEPOSITS,
        METHANE_POOLS, ICE_CRYSTALS, EXPLOSIVE_GASES, STRONG_MAGNETOSPHERE, VIBRANT_AURORAS, SALT_FLATS, CANYONS,
        PERPETUAL_DAYLIGHT, PERPETUAL_OVERCAST, DRY_SEABEDS, MAGMA_SEAS, SUPERVOLCANOES, ASH_CLOUDS, VAST_RUINS,
        MUTATED_FLORA, TERRAFORMED, EXTREME_TEMPERATURES, EXTREME_PRESSURE, DIVERSE_LIFE, SCARCE_LIFE, FOSSILS,
        WEAK_GRAVITY, STRONG_GRAVITY, CRUSHING_GRAVITY, TOXIC_ATMOSPHERE, CORROSIVE_ATMOSPHERE, BREATHABLE_ATMOSPHERE,
        THIN_ATMOSPHERE, JOVIAN, ROCKY, VOLCANIC, FROZEN, SWAMP, BARREN, TEMPERATE, JUNGLE, OCEAN, RADIOACTIVE,
        MICRO_GRAVITY_ANOMALIES, DEBRIS_CLUSTER, DEEP_CRATERS, SHALLOW_CRATERS, UNSTABLE_COMPOSITION, HOLLOWED_INTERIOR,
        STRIPPED
    }
}
